CREATE TABLE Reclamacao(
    reclamacao_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    motivo_id INT NOT NULL,
    reclamante_id INT NOT NULL,
    procurador_id INT,
    titulo VARCHAR(10) NOT NULL UNIQUE,
    situacao VARCHAR(75) NOT NULL,
    data_abertura DATE NOT NULL,
    ultima_mudanca TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    criador VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (reclamante_id) REFERENCES Reclamantes(reclamante_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (motivo_id) REFERENCES Motivos(motivo_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (procurador_id) REFERENCES Procuradores(procurador_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);