[package]
name = "proarc_connection"
version = "0.1.0"
edition = "2021"

[dependencies]
proarc_database = { path = "../proarc_database" }
proarc_file_transfer = { path = "../proarc_file_transfer" }

tokio = { version = "1.0", features = ["full"] }
dotenvy = "0.15.7"
